baseURL = "https://blog.welcomattic.com"
title = "welcomattic blog"
paginate = 5
theme = "PaperMod"
#languageCode = "fr-fr"
#copyright = "© {year}"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  env = "production"
  dateFormat = "2 Jan 2006"
  author = "welcomattic"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  [params.homeInfoParams]
    Title = "Hi there \U0001F44B"
    Content = "Welcome to my blog"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/welcomattic"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/welcomattic"


  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog/"

[[menu.main]]
  identifier = "talks"
  name = "talks"
  title = "Talks"
  url = "/talks/"

[[menu.main]]
  identifier = "oss"
  name = "oss"
  title = "OSS"
  url = "/oss/"

[[menu.main]]
  identifier = "veille"
  name = "veille"
  title = "Veille"
  url = "/veille/"


