baseURL = "https://blog.welcomattic.com"
title = "welcomattic"
paginate = 5
theme = "PaperMod"
language = "fr"
enableRobotsTXT = true
enableInlineShortcodes = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true

[params]
  env = "production"
  dateFormat = "2 Jan 2006"
  author = "welcomattic"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  mainSections = [ "blog", "veille" ]
  [params.homeInfoParams]
    Title = "Hi, I'm Mathieu"
    Content = "Web developer @ JoliCode"
    imageUrl = "/img/profile_image.jpg"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/welcomattic"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/welcomattic"

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
    safari_pinned_tab = "/safari-pinned-tab.svg"

[privacy]
  [privacy.twitter]
  disabled = false
  enableDNT = true
  simple = true

  [privacy.instagram]
  disabled = false
  simple = true

  [privacy.youtube]
  disabled = false
  privacyEnhanced = true

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false
    style = "monokai"

[[menu.main]]
  identifier = "about"
  name = "🏡"
  title = "About"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog/"

[[menu.main]]
  identifier = "talks"
  name = "talks"
  title = "Talks"
  url = "/talks/"

[[menu.main]]
  identifier = "oss"
  name = "oss"
  title = "OSS"
  url = "/oss/"

[[menu.main]]
  identifier = "veille"
  name = "veille"
  title = "Veille"
  url = "/veille/"


